name: Deploy feature branches to non-prod env

on:
  push:
    branches:
      feature*
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-f26a0e7f744890f2d2a62ca98-nonprodbucket-nsggpmunn7cl
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws creds
        uses: actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Deploy bundle to bucket
        run: |
            echo 'copying files to s3 bucket'
            aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
